console.log("EntityConstants");


const ENTITY_CLIENT = "CLIENT";

const ENTITY_CLIENT_TABLE = "Clients";

const ENTITY_CLIENT_ID = "ClientID";



const ACTION_CREATE = "CREATE";
const ACTION_UPDATE = "UPDATE";
const ACTION_DELETE = "DELETE";
const ACTION_RESTORE = "RESTORE";



const PERMISSION_CLIENT_CREATE = "CLIENT_CREATE";
const PERMISSION_CLIENT_UPDATE = "CLIENT_UPDATE";
const PERMISSION_CLIENT_DELETE = "CLIENT_DELETE";
const PERMISSION_CLIENT_READ = "CLIENT_READ";



globalThis.ENTITY_CLIENT =
ENTITY_CLIENT;


globalThis.ENTITY_CLIENT_TABLE =
ENTITY_CLIENT_TABLE;


globalThis.ENTITY_CLIENT_ID =
ENTITY_CLIENT_ID;



globalThis.ACTION_CREATE =
ACTION_CREATE;

globalThis.ACTION_UPDATE =
ACTION_UPDATE;

globalThis.ACTION_DELETE =
ACTION_DELETE;

globalThis.ACTION_RESTORE =
ACTION_RESTORE;



globalThis.PERMISSION_CLIENT_CREATE =
PERMISSION_CLIENT_CREATE;

globalThis.PERMISSION_CLIENT_UPDATE =
PERMISSION_CLIENT_UPDATE;

globalThis.PERMISSION_CLIENT_DELETE =
PERMISSION_CLIENT_DELETE;

globalThis.PERMISSION_CLIENT_READ =
PERMISSION_CLIENT_READ;



console.log(
"EntityConstants READY"
);