console.log("EntityConstants");


const EntityConstants = {


version:"0.4.0",



ENTITY_CLIENT:"CLIENT",

ENTITY_CLIENT_TABLE:"Clients",

ENTITY_CLIENT_ID:"ClientID",




EVENT_CLIENT_CREATED:"CLIENT_CREATED",
EVENT_CLIENT_UPDATED:"CLIENT_UPDATED",
EVENT_CLIENT_DELETED:"CLIENT_DELETED",
EVENT_CLIENT_RESTORED:"CLIENT_RESTORED",




ACTION_CREATE:"CREATE",
ACTION_UPDATE:"UPDATE",
ACTION_DELETE:"DELETE",
ACTION_RESTORE:"RESTORE",




PERMISSION_CLIENT_CREATE:"CLIENT_CREATE",
PERMISSION_CLIENT_UPDATE:"CLIENT_UPDATE",
PERMISSION_CLIENT_DELETE:"CLIENT_DELETE",
PERMISSION_CLIENT_READ:"CLIENT_READ"



};





globalThis.EntityConstants =
EntityConstants;



globalThis.ENTITY_CLIENT =
EntityConstants.ENTITY_CLIENT;


globalThis.ENTITY_CLIENT_TABLE =
EntityConstants.ENTITY_CLIENT_TABLE;


globalThis.ENTITY_CLIENT_ID =
EntityConstants.ENTITY_CLIENT_ID;



globalThis.EVENT_CLIENT_CREATED =
EntityConstants.EVENT_CLIENT_CREATED;

globalThis.EVENT_CLIENT_UPDATED =
EntityConstants.EVENT_CLIENT_UPDATED;

globalThis.EVENT_CLIENT_DELETED =
EntityConstants.EVENT_CLIENT_DELETED;

globalThis.EVENT_CLIENT_RESTORED =
EntityConstants.EVENT_CLIENT_RESTORED;




globalThis.ACTION_CREATE =
EntityConstants.ACTION_CREATE;


globalThis.ACTION_UPDATE =
EntityConstants.ACTION_UPDATE;


globalThis.ACTION_DELETE =
EntityConstants.ACTION_DELETE;


globalThis.ACTION_RESTORE =
EntityConstants.ACTION_RESTORE;



globalThis.PERMISSION_CLIENT_CREATE =
EntityConstants.PERMISSION_CLIENT_CREATE;


globalThis.PERMISSION_CLIENT_UPDATE =
EntityConstants.PERMISSION_CLIENT_UPDATE;


globalThis.PERMISSION_CLIENT_DELETE =
EntityConstants.PERMISSION_CLIENT_DELETE;


globalThis.PERMISSION_CLIENT_READ =
EntityConstants.PERMISSION_CLIENT_READ;



console.log(
"EntityConstants READY v"
+
EntityConstants.version
);